Class {
	#name : #BlFigmaLoaderTest,
	#superclass : #TestCase,
	#category : #'Bloc-Figma'
}

{ #category : #tests }
BlFigmaLoaderTest >> exampleSelection [

	^ '[{
	"id": "502:7628",
	"type": "RECTANGLE",
	"name": "Rectangle 116",
	"isAsset": false,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 1,
				"g": 0,
				"b": 0
			},
			"boundVariables": {}
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L271.304 0L271.304 536L0 536L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			182.6956558227539
		],
		[
			0,
			1,
			398
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-681.3043212890625
		],
		[
			0,
			1,
			-9879
		]
	],
	"x": 182.6956558227539,
	"y": 398,
	"width": 271.3043518066406,
	"height": 536,
	"absoluteBoundingBox": {
		"x": -681.3043212890625,
		"y": -9879,
		"width": 271.3043518066406,
		"height": 536
	},
	"absoluteRenderBounds": {
		"x": -681.3043212890625,
		"y": -9879,
		"width": 271.3043518066406,
		"height": 536
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": false,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "502:7632",
		"type": "GROUP"
	}
},{
	"id": "502:7631",
	"type": "RECTANGLE",
	"name": "Rectangle 117",
	"isAsset": false,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 0.25999996066093445,
				"g": 0,
				"b": 1
			},
			"boundVariables": {}
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L85.8261 0L85.8261 211L0 211L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			64
		],
		[
			0,
			1,
			561
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-800
		],
		[
			0,
			1,
			-9716
		]
	],
	"x": 64,
	"y": 561,
	"width": 85.82608795166016,
	"height": 211,
	"absoluteBoundingBox": {
		"x": -800,
		"y": -9716,
		"width": 85.82611083984375,
		"height": 211
	},
	"absoluteRenderBounds": {
		"x": -800,
		"y": -9716,
		"width": 85.82611083984375,
		"height": 211
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": false,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "502:7632",
		"type": "GROUP"
	}
}]'
]

{ #category : #tests }
BlFigmaLoaderTest >> testLoadString [
	| result |
	result := BlFigmaLoader loadString: self exampleSelection.
	self assert: result size equals: 2.
]
