Class {
	#name : #BlFigmaImagesExamples,
	#superclass : #Object,
	#category : #'Bloc-Figma-Examples'
}

{ #category : #'as yet unclassified' }
BlFigmaImagesExamples class >> imageCrop [

	<script: '(BlFigmaLoader loadStringWithTestImage: self imageCrop) rootElement inspect'>
	^ '{
	"id": "3:14",
	"type": "RECTANGLE",
	"name": "test_Image 2",
	"isAsset": true,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "IMAGE",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"scaleMode": "CROP",
			"imageTransform": [
				[
					0.6000000238418579,
					0,
					0.4000000059604645
				],
				[
					0,
					0.3960000276565552,
					0.6040000319480896
				]
			],
			"scalingFactor": 0.5,
			"filters": {
				"exposure": 0,
				"contrast": 0,
				"saturation": 0,
				"temperature": 0,
				"tint": 0,
				"highlights": 0,
				"shadows": 0
			},
			"imageHash": "ca6ff2687eea1c8fb81aaa8dbbcd4a60e1c568d4"
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L150 0L150 99L0 99L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			-998
		],
		[
			0,
			1,
			-652
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-998
		],
		[
			0,
			1,
			-652
		]
	],
	"x": -998,
	"y": -652,
	"width": 150,
	"height": 99,
	"absoluteBoundingBox": {
		"x": -998,
		"y": -652,
		"width": 150,
		"height": 99
	},
	"absoluteRenderBounds": {
		"x": -998,
		"y": -652,
		"width": 150,
		"height": 99
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": true,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	}
}'
]

{ #category : #'as yet unclassified' }
BlFigmaImagesExamples class >> imageFill [

	<script: '(BlFigmaLoader loadStringWithTestImage: self imageFill) rootElement inspect'>
	^ '{
	"id": "3:15",
	"type": "RECTANGLE",
	"name": "test_Image 3",
	"isAsset": true,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "IMAGE",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"scaleMode": "FILL",
			"imageTransform": [
				[
					1,
					0,
					0
				],
				[
					0,
					1,
					0
				]
			],
			"scalingFactor": 0.5,
			"rotation": 0,
			"filters": {
				"exposure": 0,
				"contrast": 0,
				"saturation": 0,
				"temperature": 0,
				"tint": 0,
				"highlights": 0,
				"shadows": 0
			},
			"imageHash": "ca6ff2687eea1c8fb81aaa8dbbcd4a60e1c568d4"
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L250 0L250 250L0 250L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			-1098
		],
		[
			0,
			1,
			-467
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-1098
		],
		[
			0,
			1,
			-467
		]
	],
	"x": -1098,
	"y": -467,
	"width": 250,
	"height": 250,
	"absoluteBoundingBox": {
		"x": -1098,
		"y": -467,
		"width": 250,
		"height": 250
	},
	"absoluteRenderBounds": {
		"x": -1098,
		"y": -467,
		"width": 250,
		"height": 250
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": true,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	}
}'
]

{ #category : #'as yet unclassified' }
BlFigmaImagesExamples class >> imageFit [

	<script: '(BlFigmaLoader loadStringWithTestImage: self imageFit) rootElement inspect'>
	^ '{
	"id": "3:17",
	"type": "RECTANGLE",
	"name": "test_Image 5",
	"isAsset": true,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "IMAGE",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"scaleMode": "FIT",
			"imageTransform": [
				[
					1,
					0,
					0
				],
				[
					0,
					1,
					0
				]
			],
			"scalingFactor": 0.5,
			"rotation": 0,
			"filters": {
				"exposure": 0,
				"contrast": 0,
				"saturation": 0,
				"temperature": 0,
				"tint": 0,
				"highlights": 0,
				"shadows": 0
			},
			"imageHash": "ca6ff2687eea1c8fb81aaa8dbbcd4a60e1c568d4"
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L250 0L250 250L0 250L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			-707
		],
		[
			0,
			1,
			-460
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-707
		],
		[
			0,
			1,
			-460
		]
	],
	"x": -707,
	"y": -460,
	"width": 250,
	"height": 250,
	"absoluteBoundingBox": {
		"x": -707,
		"y": -460,
		"width": 250,
		"height": 250
	},
	"absoluteRenderBounds": {
		"x": -707,
		"y": -460,
		"width": 250,
		"height": 250
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": true,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	}
}'
]

{ #category : #'as yet unclassified' }
BlFigmaImagesExamples class >> imageTile [

	<script: '(BlFigmaLoader loadStringWithTestImage: self imageTile) rootElement inspect'>
	^ '{
	"id": "3:16",
	"type": "RECTANGLE",
	"name": "test_Image 4",
	"isAsset": true,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"fills": [
		{
			"type": "IMAGE",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"scaleMode": "TILE",
			"imageTransform": [
				[
					1,
					0,
					0
				],
				[
					0,
					1,
					0
				]
			],
			"scalingFactor": 0.5,
			"rotation": 0,
			"filters": {
				"exposure": 0,
				"contrast": 0,
				"saturation": 0,
				"temperature": 0,
				"tint": 0,
				"highlights": 0,
				"shadows": 0
			},
			"imageHash": "ca6ff2687eea1c8fb81aaa8dbbcd4a60e1c568d4"
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L250 0L250 250L0 250L0 0Z"
		}
	],
	"strokeGeometry": [],
	"relativeTransform": [
		[
			1,
			0,
			-707
		],
		[
			0,
			1,
			-803
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-707
		],
		[
			0,
			1,
			-803
		]
	],
	"x": -707,
	"y": -803,
	"width": 250,
	"height": 250,
	"absoluteBoundingBox": {
		"x": -707,
		"y": -803,
		"width": 250,
		"height": 250
	},
	"absoluteRenderBounds": {
		"x": -707,
		"y": -803,
		"width": 250,
		"height": 250
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": true,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"reactions": [],
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	}
}'
]
