Class {
	#name : #BlFigmaRobiExamples,
	#superclass : #Object,
	#category : #'Bloc-Figma-Examples'
}

{ #category : #'as yet unclassified' }
BlFigmaRobiExamples class >> rotatedRoby [

	<script: '(BlFigmaLoader loadString: self rotatedRoby) inspect'>
	^ '[{
	"id": "503:3568",
	"type": "FRAME",
	"name": "background",
	"isAsset": false,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"relativeTransform": [
		[
			1,
			0,
			-1.1368683772161603e-13
		],
		[
			0,
			1,
			0
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-1.1368683772161603e-13
		],
		[
			0,
			1,
			0
		]
	],
	"x": -1.1368683772161603e-13,
	"y": 0,
	"width": 250,
	"height": 250,
	"absoluteBoundingBox": {
		"x": -1.1368683772161603e-13,
		"y": 0,
		"width": 250,
		"height": 250
	},
	"absoluteRenderBounds": {
		"x": -1.1368683772161603e-13,
		"y": 0,
		"width": 250,
		"height": 250
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": false,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"fills": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 0.18333333730697632,
				"g": 0.18333333730697632,
				"b": 0.18333333730697632
			},
			"boundVariables": {}
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L250 0L250 250L0 250L0 0Z"
		}
	],
	"strokeGeometry": [],
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"paddingLeft": 0,
	"paddingRight": 0,
	"paddingTop": 0,
	"paddingBottom": 0,
	"primaryAxisAlignItems": "MIN",
	"counterAxisAlignItems": "MIN",
	"primaryAxisSizingMode": "AUTO",
	"layoutWrap": "NO_WRAP",
	"counterAxisSpacing": 0,
	"counterAxisAlignContent": "AUTO",
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"inferredAutoLayout": {
		"layoutMode": "HORIZONTAL",
		"paddingLeft": 56.69873046875,
		"paddingRight": 56.69873046875,
		"paddingTop": 56.69873046875,
		"paddingBottom": 56.69873046875,
		"counterAxisSizingMode": "FIXED",
		"primaryAxisSizingMode": "FIXED",
		"primaryAxisAlignItems": "CENTER",
		"counterAxisAlignItems": "CENTER",
		"layoutAlign": "MIN",
		"layoutGrow": 0,
		"itemSpacing": 0,
		"layoutPositioning": "AUTO"
	},
	"layoutGrids": [],
	"gridStyleId": "",
	"backgrounds": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 0.18333333730697632,
				"g": 0.18333333730697632,
				"b": 0.18333333730697632
			},
			"boundVariables": {}
		}
	],
	"backgroundStyleId": "",
	"clipsContent": true,
	"guides": [],
	"expanded": false,
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"layoutMode": "NONE",
	"counterAxisSizingMode": "FIXED",
	"horizontalPadding": 0,
	"verticalPadding": 0,
	"itemSpacing": 0,
	"overflowDirection": "NONE",
	"numberOfFixedChildren": 0,
	"overlayPositionType": "CENTER",
	"overlayBackground": {
		"type": "NONE"
	},
	"overlayBackgroundInteraction": "NONE",
	"itemReverseZIndex": false,
	"strokesIncludedInLayout": false,
	"reactions": [],
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	},
	"children": [
		{
			"id": "503:3569",
			"type": "FRAME",
			"name": "roby",
			"isAsset": true,
			"visible": true,
			"locked": false,
			"stuckNodes": [],
			"attachedConnectors": [],
			"componentPropertyReferences": null,
			"variableConsumptionMap": {},
			"boundVariables": {},
			"resolvedVariableModes": {},
			"explicitVariableModes": {},
			"opacity": 1,
			"blendMode": "PASS_THROUGH",
			"isMask": false,
			"effects": [],
			"effectStyleId": "",
			"relativeTransform": [
				[
					0.8660253882408142,
					0.5,
					56.69873046875
				],
				[
					-0.5,
					0.8660253882408142,
					106.69873046875
				]
			],
			"absoluteTransform": [
				[
					0.8660253882408142,
					0.5,
					56.69873046875
				],
				[
					-0.5,
					0.8660253882408142,
					106.69873046875
				]
			],
			"x": 56.69873046875,
			"y": 106.69873046875,
			"width": 100,
			"height": 100,
			"absoluteBoundingBox": {
				"x": 56.69873046875,
				"y": 56.69873046875,
				"width": 136.6025390625,
				"height": 136.6025390625
			},
			"absoluteRenderBounds": {
				"x": 56.69873046875,
				"y": 56.69873046875,
				"width": 136.6025390625,
				"height": 136.6025390625
			},
			"rotation": 30.00000044529205,
			"layoutAlign": "INHERIT",
			"constrainProportions": false,
			"layoutGrow": 0,
			"layoutPositioning": "AUTO",
			"minWidth": null,
			"minHeight": null,
			"maxWidth": null,
			"maxHeight": null,
			"layoutSizingHorizontal": "FIXED",
			"layoutSizingVertical": "FIXED",
			"exportSettings": [],
			"fills": [
				{
					"type": "SOLID",
					"visible": true,
					"opacity": 1,
					"blendMode": "NORMAL",
					"color": {
						"r": 1,
						"g": 1,
						"b": 1
					},
					"boundVariables": {}
				}
			],
			"fillStyleId": "",
			"strokes": [],
			"strokeStyleId": "",
			"strokeWeight": 1,
			"strokeAlign": "INSIDE",
			"strokeJoin": "MITER",
			"dashPattern": [],
			"strokeCap": "NONE",
			"strokeMiterLimit": 4,
			"fillGeometry": [
				{
					"windingRule": "NONZERO",
					"data": "M0 0L100 0L100 100L0 100L0 0Z"
				}
			],
			"strokeGeometry": [],
			"cornerRadius": 0,
			"cornerSmoothing": 0,
			"topLeftRadius": 0,
			"topRightRadius": 0,
			"bottomLeftRadius": 0,
			"bottomRightRadius": 0,
			"paddingLeft": 0,
			"paddingRight": 0,
			"paddingTop": 0,
			"paddingBottom": 0,
			"primaryAxisAlignItems": "MIN",
			"counterAxisAlignItems": "MIN",
			"primaryAxisSizingMode": "AUTO",
			"layoutWrap": "NO_WRAP",
			"counterAxisSpacing": 0,
			"counterAxisAlignContent": "AUTO",
			"strokeTopWeight": 1,
			"strokeBottomWeight": 1,
			"strokeLeftWeight": 1,
			"strokeRightWeight": 1,
			"inferredAutoLayout": {
				"layoutMode": "HORIZONTAL",
				"paddingLeft": 10,
				"paddingRight": 46.6025390625,
				"paddingTop": 10,
				"paddingBottom": 101.6025390625,
				"counterAxisSizingMode": "FIXED",
				"primaryAxisSizingMode": "FIXED",
				"primaryAxisAlignItems": "CENTER",
				"counterAxisAlignItems": "MIN",
				"layoutAlign": "STRETCH",
				"layoutGrow": 1,
				"itemSpacing": 30,
				"layoutPositioning": "AUTO"
			},
			"layoutGrids": [],
			"gridStyleId": "",
			"backgrounds": [
				{
					"type": "SOLID",
					"visible": true,
					"opacity": 1,
					"blendMode": "NORMAL",
					"color": {
						"r": 1,
						"g": 1,
						"b": 1
					},
					"boundVariables": {}
				}
			],
			"backgroundStyleId": "",
			"clipsContent": true,
			"guides": [],
			"expanded": false,
			"constraints": {
				"horizontal": "MIN",
				"vertical": "MIN"
			},
			"layoutMode": "NONE",
			"counterAxisSizingMode": "FIXED",
			"horizontalPadding": 0,
			"verticalPadding": 0,
			"itemSpacing": 0,
			"overflowDirection": "NONE",
			"numberOfFixedChildren": 0,
			"overlayPositionType": "CENTER",
			"overlayBackground": {
				"type": "NONE"
			},
			"overlayBackgroundInteraction": "NONE",
			"itemReverseZIndex": false,
			"strokesIncludedInLayout": false,
			"reactions": [],
			"playbackSettings": {
				"autoplay": true,
				"loop": true,
				"muted": false
			},
			"parent": {
				"id": "503:3568",
				"type": "FRAME"
			},
			"children": [
				{
					"id": "503:3572",
					"type": "RECTANGLE",
					"name": "greenEye",
					"isAsset": false,
					"visible": true,
					"locked": false,
					"stuckNodes": [],
					"attachedConnectors": [],
					"componentPropertyReferences": null,
					"variableConsumptionMap": {},
					"boundVariables": {},
					"resolvedVariableModes": {},
					"explicitVariableModes": {},
					"opacity": 1,
					"blendMode": "PASS_THROUGH",
					"isMask": false,
					"effects": [],
					"effectStyleId": "",
					"fills": [
						{
							"type": "SOLID",
							"visible": true,
							"opacity": 1,
							"blendMode": "NORMAL",
							"color": {
								"r": 0,
								"g": 1,
								"b": 0
							},
							"boundVariables": {}
						}
					],
					"fillStyleId": "",
					"strokes": [],
					"strokeStyleId": "",
					"strokeWeight": 1,
					"strokeAlign": "INSIDE",
					"strokeJoin": "MITER",
					"dashPattern": [],
					"strokeCap": "NONE",
					"strokeMiterLimit": 4,
					"fillGeometry": [
						{
							"windingRule": "NONZERO",
							"data": "M0 0L25 0L25 25L0 25L0 0Z"
						}
					],
					"strokeGeometry": [],
					"relativeTransform": [
						[
							1,
							0,
							65
						],
						[
							0,
							1,
							10
						]
					],
					"absoluteTransform": [
						[
							0.8660253882408142,
							0.5,
							117.9903793334961
						],
						[
							-0.5,
							0.8660253882408142,
							82.8589859008789
						]
					],
					"x": 65,
					"y": 10,
					"width": 25,
					"height": 25,
					"absoluteBoundingBox": {
						"x": 117.9903793334961,
						"y": 70.3589859008789,
						"width": 34.15062713623047,
						"height": 34.150634765625
					},
					"absoluteRenderBounds": {
						"x": 117.9903793334961,
						"y": 70.3589859008789,
						"width": 34.15062713623047,
						"height": 34.150634765625
					},
					"rotation": 0,
					"layoutAlign": "INHERIT",
					"constrainProportions": false,
					"layoutGrow": 0,
					"layoutPositioning": "AUTO",
					"minWidth": null,
					"minHeight": null,
					"maxWidth": null,
					"maxHeight": null,
					"layoutSizingHorizontal": "FIXED",
					"layoutSizingVertical": "FIXED",
					"exportSettings": [],
					"constraints": {
						"horizontal": "MIN",
						"vertical": "MIN"
					},
					"cornerRadius": 0,
					"cornerSmoothing": 0,
					"topLeftRadius": 0,
					"topRightRadius": 0,
					"bottomLeftRadius": 0,
					"bottomRightRadius": 0,
					"reactions": [],
					"strokeTopWeight": 1,
					"strokeBottomWeight": 1,
					"strokeLeftWeight": 1,
					"strokeRightWeight": 1,
					"playbackSettings": {
						"autoplay": true,
						"loop": true,
						"muted": false
					},
					"parent": {
						"id": "503:3569",
						"type": "FRAME"
					}
				},
				{
					"id": "503:3571",
					"type": "RECTANGLE",
					"name": "redEye",
					"isAsset": false,
					"visible": true,
					"locked": false,
					"stuckNodes": [],
					"attachedConnectors": [],
					"componentPropertyReferences": null,
					"variableConsumptionMap": {},
					"boundVariables": {},
					"resolvedVariableModes": {},
					"explicitVariableModes": {},
					"opacity": 1,
					"blendMode": "PASS_THROUGH",
					"isMask": false,
					"effects": [],
					"effectStyleId": "",
					"fills": [
						{
							"type": "SOLID",
							"visible": true,
							"opacity": 1,
							"blendMode": "NORMAL",
							"color": {
								"r": 1,
								"g": 0,
								"b": 0
							},
							"boundVariables": {}
						}
					],
					"fillStyleId": "",
					"strokes": [],
					"strokeStyleId": "",
					"strokeWeight": 1,
					"strokeAlign": "INSIDE",
					"strokeJoin": "MITER",
					"dashPattern": [],
					"strokeCap": "NONE",
					"strokeMiterLimit": 4,
					"fillGeometry": [
						{
							"windingRule": "NONZERO",
							"data": "M0 0L25 0L25 25L0 25L0 0Z"
						}
					],
					"strokeGeometry": [],
					"relativeTransform": [
						[
							1,
							0,
							10
						],
						[
							0,
							1,
							10
						]
					],
					"absoluteTransform": [
						[
							0.8660253882408142,
							0.5,
							70.3589859008789
						],
						[
							-0.5,
							0.8660253882408142,
							110.3589859008789
						]
					],
					"x": 10,
					"y": 10,
					"width": 25,
					"height": 25,
					"absoluteBoundingBox": {
						"x": 70.3589859008789,
						"y": 97.8589859008789,
						"width": 34.150634765625,
						"height": 34.15062713623047
					},
					"absoluteRenderBounds": {
						"x": 70.3589859008789,
						"y": 97.8589859008789,
						"width": 34.150634765625,
						"height": 34.15062713623047
					},
					"rotation": 0,
					"layoutAlign": "INHERIT",
					"constrainProportions": false,
					"layoutGrow": 0,
					"layoutPositioning": "AUTO",
					"minWidth": null,
					"minHeight": null,
					"maxWidth": null,
					"maxHeight": null,
					"layoutSizingHorizontal": "FIXED",
					"layoutSizingVertical": "FIXED",
					"exportSettings": [],
					"constraints": {
						"horizontal": "MIN",
						"vertical": "MIN"
					},
					"cornerRadius": 0,
					"cornerSmoothing": 0,
					"topLeftRadius": 0,
					"topRightRadius": 0,
					"bottomLeftRadius": 0,
					"bottomRightRadius": 0,
					"reactions": [],
					"strokeTopWeight": 1,
					"strokeBottomWeight": 1,
					"strokeLeftWeight": 1,
					"strokeRightWeight": 1,
					"playbackSettings": {
						"autoplay": true,
						"loop": true,
						"muted": false
					},
					"parent": {
						"id": "503:3569",
						"type": "FRAME"
					}
				}
			]
		}
	]
}]'
]

{ #category : #'as yet unclassified' }
BlFigmaRobiExamples class >> simpleRoby [
	<script: '(BlFigmaLoader loadString: self simpleRoby) inspect'>
	^ '[{
	"id": "503:3568",
	"type": "FRAME",
	"name": "background",
	"isAsset": false,
	"visible": true,
	"locked": false,
	"stuckNodes": [],
	"attachedConnectors": [],
	"componentPropertyReferences": null,
	"variableConsumptionMap": {},
	"boundVariables": {},
	"resolvedVariableModes": {},
	"explicitVariableModes": {},
	"opacity": 1,
	"blendMode": "PASS_THROUGH",
	"isMask": false,
	"effects": [],
	"effectStyleId": "",
	"relativeTransform": [
		[
			1,
			0,
			-1.1368683772161603e-13
		],
		[
			0,
			1,
			0
		]
	],
	"absoluteTransform": [
		[
			1,
			0,
			-1.1368683772161603e-13
		],
		[
			0,
			1,
			0
		]
	],
	"x": -1.1368683772161603e-13,
	"y": 0,
	"width": 250,
	"height": 250,
	"absoluteBoundingBox": {
		"x": -1.1368683772161603e-13,
		"y": 0,
		"width": 250,
		"height": 250
	},
	"absoluteRenderBounds": {
		"x": -1.1368683772161603e-13,
		"y": 0,
		"width": 250,
		"height": 250
	},
	"rotation": 0,
	"layoutAlign": "INHERIT",
	"constrainProportions": false,
	"layoutGrow": 0,
	"layoutPositioning": "AUTO",
	"minWidth": null,
	"minHeight": null,
	"maxWidth": null,
	"maxHeight": null,
	"layoutSizingHorizontal": "FIXED",
	"layoutSizingVertical": "FIXED",
	"exportSettings": [],
	"fills": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 0.18333333730697632,
				"g": 0.18333333730697632,
				"b": 0.18333333730697632
			},
			"boundVariables": {}
		}
	],
	"fillStyleId": "",
	"strokes": [],
	"strokeStyleId": "",
	"strokeWeight": 1,
	"strokeAlign": "INSIDE",
	"strokeJoin": "MITER",
	"dashPattern": [],
	"strokeCap": "NONE",
	"strokeMiterLimit": 4,
	"fillGeometry": [
		{
			"windingRule": "NONZERO",
			"data": "M0 0L250 0L250 250L0 250L0 0Z"
		}
	],
	"strokeGeometry": [],
	"cornerRadius": 0,
	"cornerSmoothing": 0,
	"topLeftRadius": 0,
	"topRightRadius": 0,
	"bottomLeftRadius": 0,
	"bottomRightRadius": 0,
	"paddingLeft": 0,
	"paddingRight": 0,
	"paddingTop": 0,
	"paddingBottom": 0,
	"primaryAxisAlignItems": "MIN",
	"counterAxisAlignItems": "MIN",
	"primaryAxisSizingMode": "AUTO",
	"layoutWrap": "NO_WRAP",
	"counterAxisSpacing": 0,
	"counterAxisAlignContent": "AUTO",
	"strokeTopWeight": 1,
	"strokeBottomWeight": 1,
	"strokeLeftWeight": 1,
	"strokeRightWeight": 1,
	"inferredAutoLayout": {
		"layoutMode": "HORIZONTAL",
		"paddingLeft": 75,
		"paddingRight": 75,
		"paddingTop": 75,
		"paddingBottom": 75,
		"counterAxisSizingMode": "FIXED",
		"primaryAxisSizingMode": "FIXED",
		"primaryAxisAlignItems": "CENTER",
		"counterAxisAlignItems": "CENTER",
		"layoutAlign": "MIN",
		"layoutGrow": 0,
		"itemSpacing": 0,
		"layoutPositioning": "AUTO"
	},
	"layoutGrids": [],
	"gridStyleId": "",
	"backgrounds": [
		{
			"type": "SOLID",
			"visible": true,
			"opacity": 1,
			"blendMode": "NORMAL",
			"color": {
				"r": 0.18333333730697632,
				"g": 0.18333333730697632,
				"b": 0.18333333730697632
			},
			"boundVariables": {}
		}
	],
	"backgroundStyleId": "",
	"clipsContent": true,
	"guides": [],
	"expanded": true,
	"constraints": {
		"horizontal": "MIN",
		"vertical": "MIN"
	},
	"layoutMode": "NONE",
	"counterAxisSizingMode": "FIXED",
	"horizontalPadding": 0,
	"verticalPadding": 0,
	"itemSpacing": 0,
	"overflowDirection": "NONE",
	"numberOfFixedChildren": 0,
	"overlayPositionType": "CENTER",
	"overlayBackground": {
		"type": "NONE"
	},
	"overlayBackgroundInteraction": "NONE",
	"itemReverseZIndex": false,
	"strokesIncludedInLayout": false,
	"reactions": [],
	"playbackSettings": {
		"autoplay": true,
		"loop": true,
		"muted": false
	},
	"parent": {
		"id": "0:1",
		"type": "PAGE"
	},
	"children": [
		{
			"id": "503:3569",
			"type": "FRAME",
			"name": "roby",
			"isAsset": true,
			"visible": true,
			"locked": false,
			"stuckNodes": [],
			"attachedConnectors": [],
			"componentPropertyReferences": null,
			"variableConsumptionMap": {},
			"boundVariables": {},
			"resolvedVariableModes": {},
			"explicitVariableModes": {},
			"opacity": 1,
			"blendMode": "PASS_THROUGH",
			"isMask": false,
			"effects": [],
			"effectStyleId": "",
			"relativeTransform": [
				[
					1,
					0,
					75
				],
				[
					0,
					1,
					75
				]
			],
			"absoluteTransform": [
				[
					1,
					0,
					75
				],
				[
					0,
					1,
					75
				]
			],
			"x": 75,
			"y": 75,
			"width": 100,
			"height": 100,
			"absoluteBoundingBox": {
				"x": 75,
				"y": 75,
				"width": 100,
				"height": 100
			},
			"absoluteRenderBounds": {
				"x": 75,
				"y": 75,
				"width": 100,
				"height": 100
			},
			"rotation": 0,
			"layoutAlign": "INHERIT",
			"constrainProportions": false,
			"layoutGrow": 0,
			"layoutPositioning": "AUTO",
			"minWidth": null,
			"minHeight": null,
			"maxWidth": null,
			"maxHeight": null,
			"layoutSizingHorizontal": "FIXED",
			"layoutSizingVertical": "FIXED",
			"exportSettings": [],
			"fills": [
				{
					"type": "SOLID",
					"visible": true,
					"opacity": 1,
					"blendMode": "NORMAL",
					"color": {
						"r": 1,
						"g": 1,
						"b": 1
					},
					"boundVariables": {}
				}
			],
			"fillStyleId": "",
			"strokes": [],
			"strokeStyleId": "",
			"strokeWeight": 1,
			"strokeAlign": "INSIDE",
			"strokeJoin": "MITER",
			"dashPattern": [],
			"strokeCap": "NONE",
			"strokeMiterLimit": 4,
			"fillGeometry": [
				{
					"windingRule": "NONZERO",
					"data": "M0 0L100 0L100 100L0 100L0 0Z"
				}
			],
			"strokeGeometry": [],
			"cornerRadius": 0,
			"cornerSmoothing": 0,
			"topLeftRadius": 0,
			"topRightRadius": 0,
			"bottomLeftRadius": 0,
			"bottomRightRadius": 0,
			"paddingLeft": 0,
			"paddingRight": 0,
			"paddingTop": 0,
			"paddingBottom": 0,
			"primaryAxisAlignItems": "MIN",
			"counterAxisAlignItems": "MIN",
			"primaryAxisSizingMode": "AUTO",
			"layoutWrap": "NO_WRAP",
			"counterAxisSpacing": 0,
			"counterAxisAlignContent": "AUTO",
			"strokeTopWeight": 1,
			"strokeBottomWeight": 1,
			"strokeLeftWeight": 1,
			"strokeRightWeight": 1,
			"inferredAutoLayout": {
				"layoutMode": "HORIZONTAL",
				"paddingLeft": 10,
				"paddingRight": 10,
				"paddingTop": 10,
				"paddingBottom": 65,
				"counterAxisSizingMode": "FIXED",
				"primaryAxisSizingMode": "FIXED",
				"primaryAxisAlignItems": "CENTER",
				"counterAxisAlignItems": "MIN",
				"layoutAlign": "STRETCH",
				"layoutGrow": 1,
				"itemSpacing": 30,
				"layoutPositioning": "AUTO"
			},
			"layoutGrids": [],
			"gridStyleId": "",
			"backgrounds": [
				{
					"type": "SOLID",
					"visible": true,
					"opacity": 1,
					"blendMode": "NORMAL",
					"color": {
						"r": 1,
						"g": 1,
						"b": 1
					},
					"boundVariables": {}
				}
			],
			"backgroundStyleId": "",
			"clipsContent": true,
			"guides": [],
			"expanded": true,
			"constraints": {
				"horizontal": "MIN",
				"vertical": "MIN"
			},
			"layoutMode": "NONE",
			"counterAxisSizingMode": "FIXED",
			"horizontalPadding": 0,
			"verticalPadding": 0,
			"itemSpacing": 0,
			"overflowDirection": "NONE",
			"numberOfFixedChildren": 0,
			"overlayPositionType": "CENTER",
			"overlayBackground": {
				"type": "NONE"
			},
			"overlayBackgroundInteraction": "NONE",
			"itemReverseZIndex": false,
			"strokesIncludedInLayout": false,
			"reactions": [],
			"playbackSettings": {
				"autoplay": true,
				"loop": true,
				"muted": false
			},
			"parent": {
				"id": "503:3568",
				"type": "FRAME"
			},
			"children": [
				{
					"id": "503:3572",
					"type": "RECTANGLE",
					"name": "greenEye",
					"isAsset": false,
					"visible": true,
					"locked": false,
					"stuckNodes": [],
					"attachedConnectors": [],
					"componentPropertyReferences": null,
					"variableConsumptionMap": {},
					"boundVariables": {},
					"resolvedVariableModes": {},
					"explicitVariableModes": {},
					"opacity": 1,
					"blendMode": "PASS_THROUGH",
					"isMask": false,
					"effects": [],
					"effectStyleId": "",
					"fills": [
						{
							"type": "SOLID",
							"visible": true,
							"opacity": 1,
							"blendMode": "NORMAL",
							"color": {
								"r": 0,
								"g": 1,
								"b": 0
							},
							"boundVariables": {}
						}
					],
					"fillStyleId": "",
					"strokes": [],
					"strokeStyleId": "",
					"strokeWeight": 1,
					"strokeAlign": "INSIDE",
					"strokeJoin": "MITER",
					"dashPattern": [],
					"strokeCap": "NONE",
					"strokeMiterLimit": 4,
					"fillGeometry": [
						{
							"windingRule": "NONZERO",
							"data": "M0 0L25 0L25 25L0 25L0 0Z"
						}
					],
					"strokeGeometry": [],
					"relativeTransform": [
						[
							1,
							0,
							65
						],
						[
							0,
							1,
							10
						]
					],
					"absoluteTransform": [
						[
							1,
							0,
							140
						],
						[
							0,
							1,
							85
						]
					],
					"x": 65,
					"y": 10,
					"width": 25,
					"height": 25,
					"absoluteBoundingBox": {
						"x": 140,
						"y": 85,
						"width": 25,
						"height": 25
					},
					"absoluteRenderBounds": {
						"x": 140,
						"y": 85,
						"width": 25,
						"height": 25
					},
					"rotation": 0,
					"layoutAlign": "INHERIT",
					"constrainProportions": false,
					"layoutGrow": 0,
					"layoutPositioning": "AUTO",
					"minWidth": null,
					"minHeight": null,
					"maxWidth": null,
					"maxHeight": null,
					"layoutSizingHorizontal": "FIXED",
					"layoutSizingVertical": "FIXED",
					"exportSettings": [],
					"constraints": {
						"horizontal": "MIN",
						"vertical": "MIN"
					},
					"cornerRadius": 0,
					"cornerSmoothing": 0,
					"topLeftRadius": 0,
					"topRightRadius": 0,
					"bottomLeftRadius": 0,
					"bottomRightRadius": 0,
					"reactions": [],
					"strokeTopWeight": 1,
					"strokeBottomWeight": 1,
					"strokeLeftWeight": 1,
					"strokeRightWeight": 1,
					"playbackSettings": {
						"autoplay": true,
						"loop": true,
						"muted": false
					},
					"parent": {
						"id": "503:3569",
						"type": "FRAME"
					}
				},
				{
					"id": "503:3571",
					"type": "RECTANGLE",
					"name": "redEye",
					"isAsset": false,
					"visible": true,
					"locked": false,
					"stuckNodes": [],
					"attachedConnectors": [],
					"componentPropertyReferences": null,
					"variableConsumptionMap": {},
					"boundVariables": {},
					"resolvedVariableModes": {},
					"explicitVariableModes": {},
					"opacity": 1,
					"blendMode": "PASS_THROUGH",
					"isMask": false,
					"effects": [],
					"effectStyleId": "",
					"fills": [
						{
							"type": "SOLID",
							"visible": true,
							"opacity": 1,
							"blendMode": "NORMAL",
							"color": {
								"r": 1,
								"g": 0,
								"b": 0
							},
							"boundVariables": {}
						}
					],
					"fillStyleId": "",
					"strokes": [],
					"strokeStyleId": "",
					"strokeWeight": 1,
					"strokeAlign": "INSIDE",
					"strokeJoin": "MITER",
					"dashPattern": [],
					"strokeCap": "NONE",
					"strokeMiterLimit": 4,
					"fillGeometry": [
						{
							"windingRule": "NONZERO",
							"data": "M0 0L25 0L25 25L0 25L0 0Z"
						}
					],
					"strokeGeometry": [],
					"relativeTransform": [
						[
							1,
							0,
							10
						],
						[
							0,
							1,
							10
						]
					],
					"absoluteTransform": [
						[
							1,
							0,
							85
						],
						[
							0,
							1,
							85
						]
					],
					"x": 10,
					"y": 10,
					"width": 25,
					"height": 25,
					"absoluteBoundingBox": {
						"x": 85,
						"y": 85,
						"width": 25,
						"height": 25
					},
					"absoluteRenderBounds": {
						"x": 85,
						"y": 85,
						"width": 25,
						"height": 25
					},
					"rotation": 0,
					"layoutAlign": "INHERIT",
					"constrainProportions": false,
					"layoutGrow": 0,
					"layoutPositioning": "AUTO",
					"minWidth": null,
					"minHeight": null,
					"maxWidth": null,
					"maxHeight": null,
					"layoutSizingHorizontal": "FIXED",
					"layoutSizingVertical": "FIXED",
					"exportSettings": [],
					"constraints": {
						"horizontal": "MIN",
						"vertical": "MIN"
					},
					"cornerRadius": 0,
					"cornerSmoothing": 0,
					"topLeftRadius": 0,
					"topRightRadius": 0,
					"bottomLeftRadius": 0,
					"bottomRightRadius": 0,
					"reactions": [],
					"strokeTopWeight": 1,
					"strokeBottomWeight": 1,
					"strokeLeftWeight": 1,
					"strokeRightWeight": 1,
					"playbackSettings": {
						"autoplay": true,
						"loop": true,
						"muted": false
					},
					"parent": {
						"id": "503:3569",
						"type": "FRAME"
					}
				}
			]
		}
	]
}]'
]
