Class {
	#name : #BlFigmaTextTest,
	#superclass : #TestCase,
	#category : #'Bloc-Figma-Tests'
}

{ #category : #running }
BlFigmaTextTest >> testTextAlignCenterBottom [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignCenterMiddle [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignCenterTop [
	super setUp.

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignLeftBottom [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignLeftMiddle [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignLeftTop [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignRightBottom [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignRightMiddle [

	super setUp

	"Put here a common initialization logic for tests"
]

{ #category : #running }
BlFigmaTextTest >> testTextAlignRightTop [

	super setUp

	"Put here a common initialization logic for tests"
]
